spring:
  profiles:
    active: local
  devtools:
    livereload:
      enabled: true

handlebars:
  suffix: .html
  cache: false

---
spring:
  profiles: local
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  freemarker:
    cache: false

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/baezzangee-local;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true

---
spring:
  profiles: dev
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://baezzangee-dev.cgemfjqbmqzy.ap-northeast-2.rds.amazonaws.com:3306/baezzangee-dev?serverTimeZone=UTC&verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}